import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Menu from '../../app/Models/Menu';

export default class extends BaseSeeder {
  public async run () {
    // Write your database queries inside the run method
    Menu.createMany([
        {
            id: 1,
            parentId: 0,
            title: 'Dashboard',
            icon: 'home',
            link: '/',
            sort: 1,
            isActive: true,
        },
        {
            id:2,
            parentId: 0,
            title: 'Katalog',
            icon: 'katalog',
            link: '#',
            sort: 2,
            isActive: false,
        },
        {
            id: 3,
            parentId: 2,
            title: 'Kategori',
            icon: 'kategori',
            link: 'katalog/kategori',
            sort: 1,
            isActive: false,
        },
        {
            id: 4,
            parentId: 2,
            title: 'Produk',
            icon: 'Produk',
            link: 'katalog/produk',
            sort: 2,
            isActive: false,
        },
        {
            id: 5,
            parentId: 0,
            title: 'Penjualan',
            icon: 'cart',
            link: 'penjualan',
            sort: 3,
            isActive: false,
        },
        {
            id: 6,
            parentId: 0,
            title: 'Pembalian',
            icon: 'cart',
            link: 'pembelian',
            sort: 4,
            isActive: false,
        },
        {
            id: 7,
            parentId: 0,
            title: 'Management Stok',
            icon: 'cart',
            link: '#',
            sort: 5,
            isActive: false,
        },
        {
            id: 8,
            parentId: 7,
            title: 'Stock Barang',
            icon: 'stock',
            link: '#',
            sort: 1,
            isActive: false,
        },
        {
            id: 9,
            parentId: 7,
            title: 'Stock Opname',
            icon: 'stock',
            link: '#',
            sort: 2,
            isActive: false,
        },
        {
            id: 10,
            parentId: 0,
            title: 'Diskon & Pajak',
            icon: '#',
            link: '#',
            sort: 6,
            isActive: false,
        },
        {
            id: 11,
            parentId: 10,
            title: 'Diskon',
            icon: 'diskon',
            link: '#',
            sort: 1,
            isActive: false,
        },
        {
            id: 12,
            parentId: 10,
            title: 'Pajak',
            icon: 'pajak',
            link: '#',
            sort: 2,
            isActive: false,
        },
        {
            id: 13,
            parentId: 0,
            title: 'Laporan',
            icon: 'laporan',
            link: '#',
            sort: 7,
            isActive: false,
        },
        {
            id: 14,
            parentId: 0,
            title: 'Setting',
            icon: 'gear',
            link: '#',
            sort: 8,
            isActive: false,
        },
        {
            id: 15,
            parentId: 14,
            title: 'Menu',
            icon: 'menu',
            link: '#',
            sort: 1,
            isActive: false,
        },
        {
            id: 16,
            parentId: 0,
            title: 'Users Management',
            icon: '',
            link: '#',
            sort: 9,
            isActive: false,
        },
        {
            id: 17,
            parentId: 16,
            title: 'Users',
            icon: '',
            link: '#',
            sort: 1,
            isActive: false,
        },
        {
            id: 18,
            parentId: 16,
            title: 'Roles',
            icon: '',
            link: '#',
            sort: 2,
            isActive: false,
        },
        {
            id: 19,
            parentId: 16,
            title: 'Permissions',
            icon: '',
            link: '#',
            sort: 3,
            isActive: false,
        },
        {
            id: 20,
            parentId: 0,
            title: 'Pelanggan',
            icon: '',
            link: '#',
            sort: 10,
            isActive: false,
        },
        {
            id: 21,
            parentId: 0,
            title: 'Supplier',
            icon: '',
            link: '#',
            sort: 10,
            isActive: false,
        },

    ])
  }
}
